# Update this file with new dependencies by running conda env update --file environment.yml
name: tetra
dependencies:
        - python
        - pytorch
        - numpy
        - scipy
        - matplotlib
        - scikit-image
        - jupyter
        - tqdm
